Algoritmo "exercicio18"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/11/2025
Var
   // Seção de Declarações das variáveis
   idade:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva("Qual sua idade? ")
   Leia(idade)
   Se idade>17 então
      EscrevaL("Você pode votar na próxima eleição!")
   SeNão
      EscrevaL("Você ainda não pode votar.")
   FimSe

Fimalgoritmo