Algoritmo "exercicio99"
// Descrição   : Potencia via funcao
// Autor(a)    : Christian P Vieira
// Data atual  : 08/01/2026
Var
   Base,Expoente,P: Real
Função Potencia (A, B: Real): Real
Var
Inicio
   P <- Exp(A,B)
   Retorne P
FimFunção
Inicio

   Escreva("Digite o valor da base: ")
   Leia(Base)

   Escreva("Digite o valor do expoente: ")
   Leia(Expoente)

   P <- Potencia (Base, Expoente: Real): Real

   EscrevaL(Base," ^",Expoente," =",P)

Fimalgoritmo